version: '2'

services:
  db:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=GjSNFxYnzBlt76C67wXgteDYWh3e7IpL
  ups:
      build: ./server
      user: nobody
      command: bash -c "python3 ./run_server.py"
      expose:
        - "8000"
      depends_on:
        - db